#!/bin/sh
#
# Prepares nexus environment for WPE Framework usage

# Create device nodes if they are missing
[ ! -e /dev/brcm0 ] && mknod -m a=rw /dev/brcm0 c 30 0

# Load nexus kernel modules
modules_dir="/lib/modules/`uname -r`"
[ -e ${modules_dir}/misc/nexus.ko ] && /sbin/modprobe nexus
